name: Build Wheels

on:
  workflow_dispatch:

env:
  BUILD_TYPE: base
  WHEELS_TAG: 3.9-alpine3.13

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - name: Get information
      id: info
      uses: home-assistant/actions/helpers/info@master

    - name: Get version
      id: version
      uses: home-assistant/actions/helpers/version@master
      with:
        type: ${{ env.BUILD_TYPE }}

  build:
    name: Build ${{ matrix.arch }} base image
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2.3.4

    - name: Build wheels
      uses: Claret-Srl/wheels@claret
      with:
        tag: ${{ env.WHEELS_TAG }}
        arch: ${{ matrix.arch }}
        apk: "build-base;mariadb-dev;postgresql-dev;unixodbc-dev;libffi-dev;cmake;ncurses;git"
        requirements: "requirements.txt"
        upload: "lftp"
        wheels-host: ${{ secrets.WHEELS_HOST }}      
        wheels-port: ${{ secrets.WHEELS_PORT }}
        wheels-user: ${{ secrets.WHEELS_USER }}
        wheels-key: ${{ secrets.WHEELS_KEY }}
        wheels-index: "https://claret.io/sandbox/drypatrick/wheels"
        ftp-host: ${{ secrets.FTP_HOST }}
        ftp-user: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PSW }}
        ftp-remote: "www/sandbox/drypatrick/wheels/"
        ftp-mirror-options: "--reverse --no-perms --only-missing" # --verbose
  
